### ISSUE TITLE
Travis CI failing with undefined proto errors for trivial text change PR's

### ISSUE THREAD

**Issue by davidz627** [container-storage-interface/spec#377] opened 2019-08-08 18:36 UTC
For example this PR is just text change: https://github.com/container-storage-interface/spec/pull/375

CI is failing here: https://travis-ci.org/container-storage-interface/spec/jobs/569485934

The error:
```
go install ./csi
# google.golang.org/genproto/googleapis/rpc/status
../../../../../google.golang.org/genproto/googleapis/rpc/status/status.pb.go:23:11: undefined: proto.ProtoPackageIsVersion3
make: *** [csi.a] Error 2
make: Leaving directory `/home/travis/gopath/src/github.com/container-storage-interface/spec/lib/go'
```

My assumption is one of the proto libraries/grpc version is unpinned in CI and the golang (and some other stuff) has pinned versioning. So just every once in a while CI will break for no reason.

This is an issue with the Spec. Generating the protos on a local machine isn't much better to be honest, it's always an exercise in figuring out the correct package versions to have on my workstation...

/assign @jdef @saad-ali @jieyu @julian-hj

**Comment by jieyu** [comment] 2019-08-08 23:00
We really need to move to a docker based build environment.

**Comment by saad-ali** [comment] 2019-08-09 00:14
> We really need to move to a docker based build environment.

@hakanmemisoglu: It is asking a lot, but would you be interested and willing to do this?

**Comment by tdmanv** [comment] 2019-08-09 05:01
@saad-ali Hakan is a bit swamped at the moment, but I have some time to help out. Do you have a preference for where to put the Dockerfile and upload an image? It looks like https://hub.docker.com/_/golang is almost enough to run the travis commands. The only thing missing is `unzip`

**Comment by tdmanv** [comment] 2019-08-09 22:31
@saad-ali This instance of the issue is fixed by https://github.com/container-storage-interface/spec/pull/378. 

We can also help with containerizing the build environment, but we would need to discuss where to put the Dockerfile and host the image.

**Comment by saad-ali** [comment] 2019-08-10 00:14
@tdmanv thank you very much, that would be great. Let's put it in https://quay.io/organization/k8scsi
If you share your quay username with me, I can invite you to that org

**Comment by tdmanv** [comment] 2019-08-10 16:12
@saad-ali I don't mind: https://quay.io/user/tdmanv

**Comment by saad-ali** [comment] 2019-08-12 18:32
@tdmanv invite to the org sent! Feel free to create a new repo called `csi-spec` or `spec` or something for the image in that org. Thanks again.

**Comment by tdmanv** [comment] 2019-08-12 20:22
Great thanks for the pointer. 

My preference would be to first merge https://github.com/container-storage-interface/spec/pull/378, which is required no matter what and will immediately unblock the other PRs. After I can followup with dockerizing the build. It requires makefile and travis changes so it will take a bit longer. 

What do you think?

**Comment by saad-ali** [comment] 2019-08-13 18:43
SGTM. Merged 378

**Closed** 2019-08-13 18:42 UTC

**Comment by saad-ali** [comment] 2019-08-14 20:27
@tdmanv can you and @hakanmemisoglu also make sure to [sign the CLA](https://github.com/container-storage-interface/spec/blob/master/CONTRIBUTING.md#licence-and-cla). I also sent you an email with instructions.

**Comment by tdmanv** [comment] 2019-08-14 23:19
Done! Thank you.

**Comment by saad-ali** [comment] 2019-08-14 23:21
Thank you!
