### ISSUE TITLE
CreateVolumeRequest should provide CO related volume resource information

### ISSUE THREAD

**Issue by princerachit** [container-storage-interface/spec#248] opened 2018-06-06 16:51 UTC
This issue is tightly coupled with k8s. Some storage provisioning mechanism heavily depends on the CO itself. They leverage the architecture of CO and its resources to provision volume. Before CSI the volume representative information in CO(eg. pvc in kubernetes) was passed to the custom provisioner. The onus of extracting the volume related information was offloaded to the provisioner.
The current CSI spec restricts the free flow of CO's volume resource information(eg PVC/SC in K8s) to the driver. It is however possible to pass the information through redundant declaration in the storage class parameters but this becomes hard to maintain.
I propose that the CO's should pass their volume related claims information either as a map or a more defined struct to the CSI driver.

Related issue https://github.com/kubernetes-csi/external-provisioner/issues/93

**Comment by e4jet** [comment] 2018-06-06 17:00
I agree.  This follows the flexvolume model.  
Example:
```
..."kubernetes.io/fsType":"ext3","kubernetes.io/pod.name":"mariadb-84546b4696-foobar","kubernetes.io/pod.namespace":"ateam","kubernetes.io/pod.uid":"d0f3af91-63bc-11e8-9f73-0242ac110006"
```
The plugin can then choose what to do with the CO namespaced keys (ie: ignore them or use them).

**Comment by jieyu** [comment] 2018-06-06 17:40
I am a little worried that plugins start to *depend* on those CO specific keys. One of the goal of CSI is to allow storage vendors to just write one plugin that works for most COs. Relying on CO specific keys is against that goal. A better approach would be to first class those fields that we think are absolutely necessary (e.g., topology requirements, filesystem types, etc.) in the `CreateVolumeRequest` in a CO agnostic way.

**Comment by princerachit** [comment] 2018-06-06 18:09
I don't think that providing CO specific keys would harm the CSI's intention. It is solely the responsibility of storage vendor to consume the spec. A storage provider may choose to develop plugins only for a particular CO leveraging the architecture of CO itself or they may choose a CO agnostic way. I believe that putting a constraint on CO specific keys would harm the existing methodologies being used by some vendors. While most of the information provided by the CO in the CSI spec is sufficient for many vendors, it is not sufficient for all.

What if the provided storage is an abstraction to CO native storage resource

**Comment by jieyu** [comment] 2018-06-06 18:14
@princerachit Can you provide some examples here? For instance, what information that's not opaque to CO needs to be passed to the plugin during `CreateVolumeRequest` that's not yet first classed? 

> What if the provided storage is an abstraction to CO native storage resource

Can you elaborate a bit more here? I don't quite follow this question.

**Comment by jieyu** [comment] 2018-06-06 18:34
I guess I am more curious about the why the plugin needs those information for volume provisioning purpose. For instance, i looked at the [NFS provisioner](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L61) . It uses pvc namespace and name to construct the name of the volume. However, the CSI spec already has a `name` field for the `CreateVolumeRequest`?

You also mentioned storage class name, why the plugin needs that? Wouldn't `volume_capabilities` and `parameters` be sufficient?

**Comment by princerachit** [comment] 2018-06-06 18:41
The driver launches pods in the same namespace as that of pvc in my case. Further it retrieves the storage class from k8s api by its name.

**Comment by vladimirvivien** [comment] 2018-06-12 16:22
@princerachit  So if I understand, are you asking to insert `CO-specific` keyed values in the Parameters that are passed when `csi.CreateVolume(CreateVolumeRequest.Parameters[kubernetes.io/sfType:ext4])` is invoked.  If so, that would be more of CO-specific ask, no?

**Comment by princerachit** [comment] 2018-06-12 16:45
@vladimirvivien Yes. But I am wondering if we could have a separate message inside the request which carries this information. eg. instead of receiving it in the CreateVolumeRequest.Parameters map we could have a separate map CreateVolumeRequest.COParameters.

**Comment by jdef** [comment] 2018-06-12 16:53
IMO using CO-specific parameters is generally against the spirit of the
spec, given that plugins are intended to work across multiple COs. It
sounds like the OP is trying to tackle a problem that's more related to the
design/arch of a specific CO vs. CSI. I.e. this should probably be taken up
for discussion within k8s SIG-storage.

**Comment by princerachit** [comment] 2018-06-12 16:58
@jdef noted. I will put this issue in k8s SIG-storage.

**Comment by vladimirvivien** [comment] 2018-06-12 21:05
@princerachit what @jdef  says.  Please bring your concern to the Kubernetes CSI working group as this is a CO-specific ask.

**Comment by kfox1111** [comment] 2018-06-12 21:21
My 2 cents here... I wrote a csi driver intended to fit into the k8s view of pods. I want a csi volume to track the lifecycle of the pod. it gets created when the pod is created. it goes away when the pod goes away. I plumbed it up assuming that the podid would be used as the volumeid. In my reading of the spec I didn't see anything that prevented this behaviour. But there currently is a lack of plumbing on the k8s side to do so. Perhaps rather then passing coe specific info into the csi driver, the plumbing on the k8s side decides what volumeid passing behavior to use?

**Comment by vladimirvivien** [comment] 2018-06-13 12:02
While I don't like the idea of introducing CO-specific params in CSI calls, maybe what is needed is to extend the spec with the ability for the driver to query the CO. Thus have the CO expose gRPC service endpoints to be queried by the driver for CO-specific info (i.e. a driver registry request, storage metada request for a specific volumeHandle, etc)

**Comment by jdef** [comment] 2018-06-13 13:41
@jsafrane, @vladimirvivien thanks, each of you, for your thoughts.

> ... it's going to be main extension point for anything that looks like volumes in COs...

I don't think I agree with this statement. The examples provided (configuration as a volume, secrets as a volume) are illustrations of solving Some Other Problem (e.g. how do we expose configuration objects to containers?) by overloading a pre-existing API, because of reasons...  and in this case, that's a "volumes" API. IMO they're not shining examples of the primary use cases that CSI is intending to address. Does that make it impossible to use/abuse CSI for such things? No, not really. It's entirely plausible to write a CSI plugin whose backend is some secret store. And, I'd argue, it's possible to do that without the addition of CO-specific, first-class fields to the CSI spec. If a vendor ONLY needs/wants to support a specific CO, then that's basically up to the vendor. If the vendor is k8s, and "k8s as the vendor" only wants to support "k8s as the CO" - then that could be reasonable. The CO owners have previously discussed "shim" plugins that are CO-specific and that they might be useful in some cases, and also that they're **NOT** the norm. In general, since one of CSI's goals is to make **less** work for vendors, a vendor writing a CO-specific plugin sounds like someone maybe making more work for themselves if their overall goal is to support multiple COs.

> There are 3rd party vendors who implement their own configuration and especially secret sources, it can read secrets from highly protected vault...

This sounds like a CO/{config,secrets}-vendor integration problem, and not a CSI problem. How do you think this relates to CSI?

> I know very little about gRPC / protocol buffers, but could we for example declare that field numbers > 100000 in every message are reserved for CO extensions?

I think this is putting the cart before the horse. The first question is "should CSI expose CO-specific extension points?". Let's answer that first. I haven't yet seen any convincing, concrete use cases to support this.

> ... have the CO expose gRPC service endpoints to be queried by the driver...

We've successfully avoided, so far, defining any gRPC services on the CO-side of the house. I think that the "CO-specific info" you're asking for assumes that CO's can align on some subset of control/data elements CO's could/should provide to a plugin. I'm not very optimistic that we'll find much overlap among CO's. So far, we can't even agree how to identify a "user". I also quite like that the CSI spec is tightly focused on the storage control plane. Exposing gRPC services on the CO would begin to define a CO control plane and that feels a bit out of scope and not very aligned with the goals of the spec.

**Comment by smarterclayton** [comment] 2018-06-13 14:21
An interesting point (from the Kubernetes point of view) is that CSI was intended to be a storage abstraction for Kubernetes (which quite wisely grew to be a storage abstraction for multiple platforms).    One type of storage is remote attachable storage.  Another type is local attached storage.  If CSI evolved as a spec into something that is much more about remote attachable storage, maybe it's just a sign that CSI in Kubernetes needs to mean something different than what the spec has evolved to here.

**Comment by jdef** [comment] 2018-06-13 15:13
@smarterclayton thanks for your comments. Was there something in my response that suggested CSI is not applicable to "local storage"? That's definitely not the picture that I was trying to paint. Though, upon further thought, I guess that depends what the scope of "local storage" is defined to be. CSI doesn't attempt to define that term (and I also don't think that it should try). CSI generally tries to focus, primarily, on a control plane protocol targeting volume life cycle management and accessibility. There's some non-protocol stuff in the spec as written, but we've tried to keep it minimal and mostly as recommendations (vs requirements).

The "configuration as a volume" and "secrets as a volume" cases presented earlier - are those considered to be part of the "local storage" arena in k8s? When I think "local storage" I think of things like LVM, whole disks, disk partitions, virtual storage masquerading as local block devices, etc. Using CSI to solve configuration and secrets integration feels like shoehorning "the tool you have on hand" because it happens to be the nearest fit. And this may be perfectly acceptable on a per-CO basis... CSI doesn't pass judgement here. That said, I have doubts about baking in first-class support for such into the spec, or recommending such as a generalized, cross-CO compatible approach.

**Comment by childsb** [comment] 2018-06-13 16:03
Though it would be *nice* for every CSI plugin to be CO agnostic, this won't be the case.  I've had multiple CSI plugin developers want to specifically focus on a single platform, or provide an enhanced feature set for one platform thats not possible on the other.

* There are file oriented extensions that fit very nicely through the CSI interface as extensions to the CO.. Kube wants to do these things, other COs may want to too.. These CSI/CO functional shims probably wouldn't be CO agnostic... I can provide multiple examples of Kubernetes FLEX plugins which copy files into a container, manipulate a container as part of attaching the storage or similar.

* Things like 'local storage' are common across COs but may have a different feature set depending on the CO or Host.

I think we should step back and not get too stuck in the details of what each CO may or may not do with the interface.  If we can enable all of this function with a very minimal set of API, why not?

**Comment by saad-ali** [comment] 2018-06-13 17:02
We discussed this at the CSI community meeting today.

Conclusion was that on the `CreateVolumeRequest` the existing opaque `parameters` field should be sufficient to allow passing in workload information (it would require the driver be paired with a sidecar container, external-provisioner, that knows how to set the field).

On the `NodePublishVolumeRequest` (mount) side, we agreed there should be a way to pass in workload information. We agreed on adding a new `Workload` struct that contains an opaque map that the CO can fill with whatever makes sense for it (e.g. for Kubernetes, pod namespace/name/uid).

**Comment by jsafrane** [comment] 2018-06-18 13:53
There is no recording of the meeting, so from the comment above the solution is:

```
message NodePublishVolumeRequest {
    // <snip>

    // CO workload that requests the volume.
    // This is an OPTIONAL field.
    Workload workload = 9;
}

// Parameters of a CO workload that lead to CSI request.
message Workload {
    // CO specific parameters of the workload, such as workload name.
    map<string, string> parameters = 1;
}
```

Did you agree on its handling? Does the plugin *need* to use `workload` when it's specified? Does it *need* to understand all provided `parameters`?

**Comment by jsafrane** [comment] 2018-06-22 09:30
Fix: #252

**Comment by cpuguy83** [comment] 2018-06-29 20:04
This use case is feature creep at its finest.

**Comment by jdef** [comment] 2018-06-29 23:39
I'm not in love with the proposed solution either. I suggested that it's
possible to pass additional parameters oob via grpc metadata. The end
result is still the same, functionally... just less formalized. It was
argued that it's better to see these things in the api vs. metadata because
its more clear what's happening.... and plugin authors are just going to
hack around the spec anyway if there are no per workload fields for co data.

This is a huge hole being poked in the api and I'm pretty sure it's going
to be abused.

**Comment by cpuguy83** [comment] 2018-06-30 20:21
I will go out on a limb here and say I am vehemently opposed to this solution.

In the same way that SP's provide different APIs for k/v stores, block storage, file storage, etc we should not try and cram every use case for some kind of storage into CSI.

**Comment by gnufied** [comment] 2018-07-02 20:43
My 2 cents on this is - I think any attempt to discourage users from passing custom workload specific data to plugin is far removed from reality.  In last 2 months or so, I have reviewed several flexvolume plugins (of which CSI is natural successor) that use workload information for very reasonable things.  For example - someone wants to mount HDFS file system over fuse for workload specific map-reduce job.  

Either these users will abuse one of the existing parameters or simply stay away from CSI.

**Comment by jdef** [comment] 2018-07-03 13:32
... mount HDFS filesystem over fuse...

Ok, I'll bite since this seems like a concrete use case. Why are the newly
proposed API changes needed for this, exactly? Please explain it to me as
if I was not intimately familiar with k8s or flex volumes.

**Comment by childsb** [comment] 2018-07-09 10:34
(In kubernetes) there are multiple scenarios where the CSI driver needs to know information about the "workload" thats using the storage to provide advanced security or other workload manipulation related to storage.. One of the founding goals of CSI (though not specifically documented) is to replace the FLEX interface in kubernetes in a way that's useful to other COs.  The kube-flex currently provides workload information, and there are multiple FLEX plugins which rely heavily on it..

Some specific kubernetes use cases--
* Injection of data into pod that volume is attaching to
* Injection of secrets / credentials / certificates into running POD
* UID / GID / Permissions of running container
* Storage class / performance characteristics of storage request. 
* Passing of data/metadata from PV/PVC to volume driver (mount options, credentials, performance characteristics, quota)

I realize that formalizing some of these things is a 'non goal' in the spec, so we are really looking for enough workload information to implement this ad-hoc in COs that support/need it.  I would expect these CSI plugins to be CO dependent (not-agnostic)
 
Some broad use cases:

* Secret vault
* Kerberose integration
* directory / File pre-population

Related kube issue: https://github.com/kubernetes/kubernetes/issues/64984

And here's a small set of existing FLEX plugins which require 'workload' identifying information to work:

Kubernetes moving "service account secret" generation out of tree:
* https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/svcacct-token-volume-source.md

Hashicorp vault injecting a secret into a pod based on the info about the pod:
* https://github.com/fcantournet/kubernetes-flexvolume-vault-plugin

Flexvolume for custodia (to inject a fuse mount into a pod that has secrets)
* https://github.com/adelton/kubernetes-flexvolume-fuse

Mounting something from the container runtime into a pod

Flexvolume to mount an image at a directory in a pod
* https://github.com/dims/docker-flexvol

Mounting a directory that a node local daemon watches to abstract container runtime operations like getting a snapshot of a container as a file
* https://github.com/openshift/container-snapshot

Mounting things that might not want to have PVs but which need info from the pod (more inline pod)

Flexvolume S3 fuse mount
* https://github.com/informatics-lab/s3-fuse-flex-volume

ZFS flexvolume mount:
* https://github.com/bakins/zfs-flex-volume

There are quite a few more examples not listed... Though these aren't 'pure' storage integrations, they are 'storage like' enough and coupled or related to the storage plugin interface & attached storage that its necessary for the more advanced use cases / security beyond simple attach/detach/provision/delete.  

I understand the backlash of opening up this additional metadata-- and i dont see a good generic way to express 'workload information' which is CO agnostic which all COs could agree.. but if we dont provide the possibility for COs to express workload identifying data through CSI then the kube-CSI implementation will be impotent.

**Comment by cpuguy83** [comment] 2018-07-09 18:00
1. Why are we defining an API here and at the same time planning to circumvent it before it's even released?
2. Most of these examples seem to want to cram what Kube (or Flexvolume drivers) is currently doing into the CSI model, this cannot work.
3. Some (all?) of these things make sense to expose as a first class entity in CSI 
    i. Storage class has been at least discussed in the past, I can't remember what the outcome was
    ii. Injection of secrets / credentials / certificates into running POD (kerberose, secret vault) -- Why does this need some workload/CO dependent options to be passed to the plugin?
   iii. UID/GID --  Discussed, but IIRC required further thought on how to properly abstract this
   iv. mount options, credentials, performance characteristics, quota -- these are all very different things... I do not consider them metadata.
      -  Credentials should be handled in the API today, is what is there not satisfactory?
      -  Mount options should be handled, but looking at NodePublish maybe not well enough for per-publish options

**Comment by cpuguy83** [comment] 2018-07-10 23:08
> What do you mean, what API are we defining/circumventing?

If someone is passing CO specific values, this is circumventing the API. It means there is now a contract between the CO and the plugin that extends beyond just CSI.

I don't mean to say that we shouldn't bring on the things that Flex is doing, but we should be more deliberate about how we do it and define a well-formed API around it rather than CO specific values (e.g. a Kubernetes annotation like `io.k8s.<foo>.<bar>=<baz>`... also not to say that the same style of API shouldn't exist, just that it ought to be defined in CSI so that the contract between the CO and the plugin is well defined here.

**Comment by saad-ali** [comment] 2018-11-05 23:53
We are addressing the use cases for Kubernetes on a case by case basis and adding support via side car containers. For example we added pod workload info last quarter. We should avoid modifying the CSI spec to whole sale pass opaque data. Please follow up with SIG-Storage on any additional use cases you may have.

**Closed by saad-ali** 2018-11-05 23:53 UTC
