### ISSUE TITLE
Proposal: Permit Named Pipe in addition to Unix Domain Socket for connectivity

### ISSUE THREAD

**Issue by friism** [container-storage-interface/spec#35] opened 2017-06-09 16:17 UTC
The connectivity section specifies use of a Unix Domain Socket (UDS): https://github.com/container-storage-interface/spec/blob/master/spec.md#connectivity

It'd like to propose that Windows Named Pipes be permitted too. Named pipes are used for gRPC by Docker when running on Windows on `npipe://./pipe/docker_engine`.

I've skimmed the spec, and I think this is the only issue that would block building a prototype implementation that can run on Windows.

Both Kubernetes and Docker Swarm have support for Windows Docker containers: 

 * https://kubernetes.io/docs/getting-started-guides/windows/
 * https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/swarm-mode

**Comment by jdef** [comment] 2017-06-09 17:18
duplicate of #10

**Closed by jdef** 2017-06-09 17:18 UTC
Labels: duplicate
