### ISSUE TITLE
Responsibility of target_path in NodePublishVolume

### ISSUE THREAD

**Issue by lpabon** [container-storage-interface/spec#147] opened 2017-11-15 22:16 UTC
The spec should define who is responsible for creating the `target_path` as defined in https://github.com/container-storage-interface/spec/blob/master/spec.md#node-service-rpc for `NodePublishVolume`.

If the responsibility is for:

* CO: Then the plugin should return an error if the target_path does not exist
* Plugin: Then the plugin should return an error (or ignore) if the path already exists
* Either: Then the CO _should_ create, if not, the plugin _must_ create it.

Any of these would be fine (I vote for at least one to be dedicated), but this should be explicitly documented on the specification.

**Comment by lpabon** [comment] 2017-11-15 22:21
I feel that the CO should do it. It would check and verify any errors before asking the CSI plugin to do something

**Comment by saad-ali** [comment] 2017-11-15 23:25
I agree this should be specified in the spec. I'm not sure what the best option is. I'm leaning slightly towards having the plugin do it to leave more power in the hands of the plugin.

**Comment by julian-hj** [comment] 2017-11-15 23:37
I recall discussing this with @jieyu a while back.  IIRC, we decided that the CO should do it, because the alternative is that the CO has to make sure the plugin has rights to create directories, which could get messy, but I could be misremembering.

**Comment by julian-hj** [comment] 2017-11-15 23:40
In fact this is a duplicate of #60.  Can we close it for the sake of tidiness?

**Comment by saad-ali** [comment] 2017-11-16 00:05
Yes! Closing as duplicate of #60. @lpabon feel free to add your comments there.

**Closed by saad-ali** 2017-11-16 00:05 UTC
